artifacts_root: artifacts


DataIngestionConfig:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1yUYxvoOouVZkkkAZ6q9i6aDbTYuqm1de/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_path: artifacts/data_ingestion